---
- name: stop and disable ntp
  service:
    name: ntpd
    state: stopped
    enabled: no
  ignore_errors: true

- name: install chrony
  ansible.builtin.yum:
    name:
      - chrony
    state: present
  notify: restart_chrony

- name: copy chrony config template
  ansible.builtin.copy:
    src: files/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart_chrony


