---

- name: Add Docker repo
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docer-ce.repo
        
#- name: Enable Docker Edge & Test repo
#  ini_file:
#    dest: /etc/yum.repos.d/docer-ce.repo
#    section: "{{ item }}"
#    option: enabled
#    value: 0
#  with_items: ['docker-ce-test', 'docker-ce-edge']

- name: Install Docker Community Edition
  ansible.builtin.dnf:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin


- name: Enable service docker, notify restart handler
  ansible.builtin.service:
    name: docker
    enabled: yes
  notify: docker_restart
